# Adjust Volume with up and down

UP add volume +4

DOWN add volume -4


# Cycle Audio (# for cycle up)
' cycle audio down

# Open File Manager of Currently opened media (doesn't work on NAS)
shift+b script_message locate-current-file

# Display File Path of Currently opened media
b show-text "🗁 Oh, du möchtest die Directory prüfen, du Stinker?\nDiese File ist hier: \n \n${path}"

# Unused: Show File Path in OSD when loading
# osd-playing-msg=${path}





shift+x osd-msg=${path}



# seek-to.lua Script: Jump to exact time

shift+s script-message-to seek_to toggle-seeker


# Quit Program

ctrl+q quit

q ignore

# Cycling Through Existing Script: Disable "None" Tracks for Audio and Subtitles.

_     script-binding cycle_video_up
SHARP script-binding cycle_audio_up
' script-binding cycle_audio_down
j     script-binding cycle_sub_up
J     script-binding cycle_sub_down



# enable shader
ö change-list glsl-shaders toggle "/home/yannik/.var/app/io.mpv.Mpv/config/mpv/shaders/adaptive-sharpen.glsl"

# Screenshots

s ignore
ctrl+s screenshot
alt+s screenshot video



# Reset Color Changes with "0"
0 set contrast 0 ; set brightness 0 ; set gamma 0 ; set hue 0 ; set saturation 0 ; show-text "🛈 Hallo, Stinker. Alle Farb‑Werte wurden zurückgesetzt."


# Reset Video Changes with "9"
9 set video-scale-y 1 ; set video-scale-x 1 ; set video-pan-x 0 ; set video-pan-y 0 ; set video-zoom 0 ; set sub-pos 100 ; set video-aspect-override 0 ; set panscan 0 ; set sub-scale 1 ; set sub-delay 0 ; show-text "🛈 Hallo, Stinker. Alle Scale- und Subtitle‑Werte wurden zurückgesetzt."






# Open Menus
alt+shift+p script-binding select/select-playlist
alt+shift+v script-binding select/select-vid
alt+shift+a script-binding select/select-aid
alt+shift+c script-binding select/select-chapter
alt+shift+s script-binding select/select-sid
alt+shift+ctrl+s script-binding select/select-subtitle-line
alt+shift+k script-binding select/select-binding
alt+shift+e script-binding select/select-edition
alt+shift+b script-binding select/select-binding



# Disable F8 + F9 Media Infos
F8 none
F9 none


# Unused: Open Menu
# ctrl+p script-binding select/menu

# Unused: Show Path
# Ctrl+Alt+p show-text "Pfad: ${path}"

# ctrl+alt+8 script-message-to context_menu open
