# Basic Settings
script-opts=autoload=yes
osc=no


# Keep the MPV window open after playback
keep-open=yes
idle=yes

# Status-Meldungen länger anzeigen lassen (Es sind Millisekunden)
osd-duration=5000

# Remember Position, Volume and Loop Status after Close
save-position-on-quit
watch-later-options=start
watch-later-options=volume




# Set Screenshot Directory
screenshot-directory=/home/yannik/Pictures/mpv  

# Change Font
osd-font='Adwaita Mono'
sub-font='Roboto Light'

# Change Colors + Font Size
osd-color='#FB8C00'  # Orange für aktiven Eintrag
osd-border-color='#000000'
osd-back-color='#000000CC'
osd-border-size=1
osd-font-size=34


# Default Audio and Subtitle Tracks
alang = en,eng,de,deu,ger #English/German
slang = en,eng,de,deu,ger #English/German


# Show File Name Instead of Title
title=${filename/no-ext}

# Hide OSD on Pause
# osd-on-pause=no






# UNUSED

# --load-context-menu=yes
