# [YTG] Set Custom Language to Display Custom Idle + Player Controls Text
language=enCustom

# [YTG] show OSC when paused
showonpause=no

# [YTG] time (in ms) before OSC hides if no mouse movement
hidetimeout=2000

# [YTG] height of the bottom hover zone (in pixels)
bottomhover_zone=130


# [YTG] title above seekbar format: "${media-title}" or "${filename}"
title=${filename/no-ext}

# [YTG] font size of the title text (above seekbar)
title_font_size=30

# [YTG] chapter title font size
chapter_title_font_size=18

# [YTG] tooltips font size
tooltip_font_size=22

# [YTG] show window on top button
ontop_button=no

# [YTG] enable loop with mouse actions on pause button
loop_in_pause=no

# [YTG] color of minimize window controls on hover
windowcontrols_min_hover=#F8BC3A

# [YTG] Seekbar Height
seekbar_height=xlarge

# [YTG] Chapter Markers
nibbles_style=single-bar

# [YTG] Hover Zones (= Show HUD when Moving Mouse)
windowcontrols_independent=no
deadzonesize=0.0

# [YTG] Icon Theme Option
icon_style=outline


# [YTG] Right Click und Middle Click auf "Play" Button disablen
play_pause_mbtn_mid_command=ignore
play_pause_mbtn_right_command=ignore

# [YTG] Change Middle Click Title Action from Save History to Show Path
title_mbtn_right_command=show-text ${path}

# [YTG] Show "..." Indicator when title is too long
truncate_title=yes
